
#
# This file contains configuration flags to customize your site
#

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"   # cleaner, softer look than default
title: Lorenzo Rossi
subtitle: "Ph.D. Candidate in Economics"
description: "Ph.D. Candidate in Economics at Ca' Foscari University of Venice. Research interests in Political Economy and Policy Evaluation."
author: "Lorenzo Rossi"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      comments: false
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
